/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */


export interface paths {
  "/auth/": {
    /** Auth Root */
    get: operations["auth_root_auth__get"];
  };
  "/auth/token/": {
    /** Token */
    post: operations["token_auth_token__post"];
  };
  "/auth/login/password/": {
    /** Login Password */
    post: operations["login_password_auth_login_password__post"];
  };
  "/auth/login/magic-link/": {
    /** Login Magic Link */
    post: operations["login_magic_link_auth_login_magic_link__post"];
  };
  "/auth/login/otp/email/": {
    /** Login Otp Email */
    post: operations["login_otp_email_auth_login_otp_email__post"];
  };
  "/auth/login/otp/phone_number/": {
    /** Login Otp Phone Number */
    post: operations["login_otp_phone_number_auth_login_otp_phone_number__post"];
  };
  "/auth/signup/": {
    /** Signup */
    post: operations["signup_auth_signup__post"];
  };
  "/auth/login/google/": {
    /** Login Google */
    post: operations["login_google_auth_login_google__post"];
  };
  "/auth/request/signup/": {
    /** Request Sign Up Email */
    post: operations["request_sign_up_email_auth_request_signup__post"];
  };
  "/auth/request/magic-link/email/": {
    /** Request Magic Link Email */
    post: operations["request_magic_link_email_auth_request_magic_link_email__post"];
  };
  "/auth/request/magic-link/sms/": {
    /** Request Magic Link Sms */
    post: operations["request_magic_link_sms_auth_request_magic_link_sms__post"];
  };
  "/auth/request/otp/email/": {
    /** Request Otp Email */
    post: operations["request_otp_email_auth_request_otp_email__post"];
  };
  "/auth/request/otp/sms/": {
    /** Request Otp Sms */
    post: operations["request_otp_sms_auth_request_otp_sms__post"];
  };
  "/auth/logout/": {
    /** Logout */
    post: operations["logout_auth_logout__post"];
  };
  "/users/": {
    /** List */
    get: operations["list_users__get"];
  };
  "/users/me/": {
    /** Get Me */
    get: operations["get_me_users_me__get"];
    /** Delete Me */
    delete: operations["delete_me_users_me__delete"];
    /** Update Me */
    patch: operations["update_me_users_me__patch"];
  };
  "/users/{user_id}/": {
    /** By Id */
    get: operations["by_id_users__user_id___get"];
  };
  "/users/available/username/{username}/": {
    /** Check Username Availability */
    get: operations["check_username_availability_users_available_username__username___get"];
  };
  "/galleries/": {
    /** List */
    get: operations["list_galleries__get"];
    /** Create */
    post: operations["create_galleries__post"];
  };
  "/galleries/{gallery_id}/": {
    /** By Id */
    get: operations["by_id_galleries__gallery_id___get"];
    /** Delete */
    delete: operations["delete_galleries__gallery_id___delete"];
    /** Update */
    patch: operations["update_galleries__gallery_id___patch"];
  };
  "/galleries/details/available/": {
    /** Check Availability */
    get: operations["check_availability_galleries_details_available__get"];
  };
  "/galleries/{gallery_id}/upload/": {
    /** Upload File */
    post: operations["upload_file_galleries__gallery_id__upload__post"];
  };
  "/galleries/{gallery_id}/sync/": {
    /** Sync */
    post: operations["sync_galleries__gallery_id__sync__post"];
  };
  "/user-access-tokens/": {
    /** List */
    get: operations["list_user_access_tokens__get"];
  };
  "/user-access-tokens/{user_access_token_id}/": {
    /** By Id */
    get: operations["by_id_user_access_tokens__user_access_token_id___get"];
    /** Delete */
    delete: operations["delete_user_access_tokens__user_access_token_id___delete"];
  };
  "/user-access-tokens/details/count/": {
    /** Count */
    get: operations["count_user_access_tokens_details_count__get"];
  };
  "/api-keys/": {
    /** List */
    get: operations["list_api_keys__get"];
    /** Create */
    post: operations["create_api_keys__post"];
  };
  "/api-keys/{api_key_id}/": {
    /** By Id */
    get: operations["by_id_api_keys__api_key_id___get"];
    /** Delete */
    delete: operations["delete_api_keys__api_key_id___delete"];
    /** Update */
    patch: operations["update_api_keys__api_key_id___patch"];
  };
  "/api-keys/{api_key_id}/generate-jwt/": {
    /** Jwt */
    get: operations["jwt_api_keys__api_key_id__generate_jwt__get"];
  };
  "/api-keys/details/available/": {
    /** Check Availability */
    get: operations["check_availability_api_keys_details_available__get"];
  };
  "/api-keys/details/count/": {
    /** Count */
    get: operations["count_api_keys_details_count__get"];
  };
  "/api-key-scopes/api-keys/{api_key_id}/scopes/{scope_id}/": {
    /** Add Scope To Api Key */
    post: operations["add_scope_to_api_key_api_key_scopes_api_keys__api_key_id__scopes__scope_id___post"];
    /** Remove Scope From Api Key */
    delete: operations["remove_scope_from_api_key_api_key_scopes_api_keys__api_key_id__scopes__scope_id___delete"];
  };
  "/pages/profile/": {
    /** Profile */
    get: operations["profile_pages_profile__get"];
  };
  "/pages/home/": {
    /** Home */
    get: operations["home_pages_home__get"];
  };
  "/pages/settings/": {
    /** Settings */
    get: operations["settings_pages_settings__get"];
  };
  "/pages/settings/api-keys/": {
    /** Settings Api Keys */
    get: operations["settings_api_keys_pages_settings_api_keys__get"];
  };
  "/pages/settings/user-access-tokens/": {
    /** Settings User Access Tokens */
    get: operations["settings_user_access_tokens_pages_settings_user_access_tokens__get"];
  };
  "/pages/styles/": {
    /** Styles */
    get: operations["styles_pages_styles__get"];
  };
  "/pages/galleries/{gallery_id}/": {
    /** Gallery */
    get: operations["gallery_pages_galleries__gallery_id___get"];
  };
  "/admin/users/": {
    /** List */
    get: operations["list_admin_users__get"];
    /** Create */
    post: operations["create_admin_users__post"];
  };
  "/admin/users/{user_id}/": {
    /** By Id */
    get: operations["by_id_admin_users__user_id___get"];
    /** Delete */
    delete: operations["delete_admin_users__user_id___delete"];
    /** Update */
    patch: operations["update_admin_users__user_id___patch"];
  };
  "/admin/galleries/{gallery_id}/": {
    /** By Id */
    get: operations["by_id_admin_galleries__gallery_id___get"];
    /** Delete */
    delete: operations["delete_admin_galleries__gallery_id___delete"];
    /** Update */
    patch: operations["update_admin_galleries__gallery_id___patch"];
  };
  "/admin/galleries/": {
    /** Create */
    post: operations["create_admin_galleries__post"];
  };
  "/admin/galleries/details/available/": {
    /** Check Availability */
    get: operations["check_availability_admin_galleries_details_available__get"];
  };
  "/admin/galleries/users/{user_id}": {
    /** List By User */
    get: operations["list_by_user_admin_galleries_users__user_id__get"];
  };
  "/admin/user-access-tokens/users/{user_id}/": {
    /** List By User */
    get: operations["list_by_user_admin_user_access_tokens_users__user_id___get"];
  };
  "/admin/user-access-tokens/{user_access_token_id}/": {
    /** By Id */
    get: operations["by_id_admin_user_access_tokens__user_access_token_id___get"];
    /** Delete */
    delete: operations["delete_admin_user_access_tokens__user_access_token_id___delete"];
  };
  "/admin/user-access-tokens/": {
    /** Create */
    post: operations["create_admin_user_access_tokens__post"];
  };
  "/admin/api-keys/users/{user_id}/": {
    /** List By User */
    get: operations["list_by_user_admin_api_keys_users__user_id___get"];
  };
  "/admin/api-keys/{api_key_id}/": {
    /** By Id */
    get: operations["by_id_admin_api_keys__api_key_id___get"];
    /** Delete */
    delete: operations["delete_admin_api_keys__api_key_id___delete"];
    /** Update */
    patch: operations["update_admin_api_keys__api_key_id___patch"];
  };
  "/admin/api-keys/": {
    /** Create */
    post: operations["create_admin_api_keys__post"];
  };
  "/admin/api-keys/details/available/": {
    /** Check Availability */
    get: operations["check_availability_admin_api_keys_details_available__get"];
  };
  "/admin/api-key-scopes/api-keys/{api_key_id}/scopes/{scope_id}/": {
    /** Add Scope To Api Key */
    post: operations["add_scope_to_api_key_admin_api_key_scopes_api_keys__api_key_id__scopes__scope_id___post"];
    /** Remove Scope From Api Key */
    delete: operations["remove_scope_from_api_key_admin_api_key_scopes_api_keys__api_key_id__scopes__scope_id___delete"];
  };
}

export type webhooks = Record<string, never>;

export interface components {
  schemas: {
    /** ApiKeyAdminCreate */
    ApiKeyAdminCreate: {
      /** Name */
      name: string;
      /**
       * Expiry
       * Format: date-time
       */
      expiry: string;
      /** User Id */
      user_id: string;
    };
    /** ApiKeyAdminUpdate */
    ApiKeyAdminUpdate: {
      /** Name */
      name?: string | null;
      /** Expiry */
      expiry?: string | null;
    };
    /** ApiKeyCreate */
    ApiKeyCreate: {
      /** Name */
      name: string;
      /**
       * Expiry
       * Format: date-time
       */
      expiry: string;
    };
    /** ApiKeyJWTResponse */
    ApiKeyJWTResponse: {
      /** Jwt */
      jwt: string;
    };
    /** ApiKeyPrivate */
    ApiKeyPrivate: {
      /** Id */
      id: string;
      /** User Id */
      user_id: string;
      /** Name */
      name: string;
      /**
       * Issued
       * Format: date-time
       */
      issued: string;
      /**
       * Expiry
       * Format: date-time
       */
      expiry: string;
    };
    /** ApiKeyUpdate */
    ApiKeyUpdate: {
      /** Name */
      name?: string | null;
      /** Expiry */
      expiry?: string | null;
    };
    /** Body_login_password_auth_login_password__post */
    Body_login_password_auth_login_password__post: {
      /**
       * Stay Signed In
       * @default false
       */
      stay_signed_in?: boolean;
      /** Grant Type */
      grant_type?: string | null;
      /** Username */
      username: string;
      /** Password */
      password: string;
      /**
       * Scope
       * @default
       */
      scope?: string;
      /** Client Id */
      client_id?: string | null;
      /** Client Secret */
      client_secret?: string | null;
    };
    /** Body_token_auth_token__post */
    Body_token_auth_token__post: {
      /**
       * Stay Signed In
       * @default false
       */
      stay_signed_in?: boolean;
      /** Grant Type */
      grant_type?: string | null;
      /** Username */
      username: string;
      /** Password */
      password: string;
      /**
       * Scope
       * @default
       */
      scope?: string;
      /** Client Id */
      client_id?: string | null;
      /** Client Secret */
      client_secret?: string | null;
    };
    /** Body_upload_file_galleries__gallery_id__upload__post */
    Body_upload_file_galleries__gallery_id__upload__post: {
      /**
       * File
       * Format: binary
       */
      file: string;
    };
    /** DetailOnlyResponse */
    DetailOnlyResponse: {
      /** Detail */
      detail: string;
    };
    /** GalleryAdminCreate */
    GalleryAdminCreate: {
      /** Name */
      name: string;
      /** Visibility Level */
      visibility_level: number;
      /** Description */
      description?: string | null;
      /** Date */
      date?: string | null;
      /** User Id */
      user_id: string;
      /** Parent Id */
      parent_id?: string | null;
    };
    /** GalleryAdminUpdate */
    GalleryAdminUpdate: {
      /** Name */
      name?: string | null;
      /** User Id */
      user_id?: string | null;
      /** Visibility Level */
      visibility_level?: number | null;
      /** Parent Id */
      parent_id?: string | null;
      /** Description */
      description?: string | null;
      /** Date */
      date?: string | null;
    };
    /** GalleryCreate */
    GalleryCreate: {
      /** Name */
      name: string;
      /** Visibility Level */
      visibility_level: number;
      /** Description */
      description?: string | null;
      /** Date */
      date?: string | null;
      /** Parent Id */
      parent_id: string;
    };
    /** GalleryPageResponse */
    GalleryPageResponse: {
      auth: components["schemas"]["GetUserSessionInfoReturn"];
      gallery: components["schemas"]["GalleryPublic"];
      /** Parents */
      parents: components["schemas"]["GalleryPublic"][];
      /** Children */
      children: components["schemas"]["GalleryPublic"][];
    };
    /** GalleryPrivate */
    GalleryPrivate: {
      /** Id */
      id: string;
      /** User Id */
      user_id: string;
      /** Name */
      name: string;
      /** Parent Id */
      parent_id: string | null;
      /** Description */
      description: string | null;
      /** Date */
      date: string | null;
      /** Visibility Level */
      visibility_level: number;
    };
    /** GalleryPublic */
    GalleryPublic: {
      /** Id */
      id: string;
      /** User Id */
      user_id: string;
      /** Name */
      name: string;
      /** Parent Id */
      parent_id: string | null;
      /** Description */
      description: string | null;
      /** Date */
      date: string | null;
    };
    /** GalleryUpdate */
    GalleryUpdate: {
      /** Name */
      name?: string | null;
      /** User Id */
      user_id?: string | null;
      /** Visibility Level */
      visibility_level?: number | null;
      /** Parent Id */
      parent_id?: string | null;
      /** Description */
      description?: string | null;
      /** Date */
      date?: string | null;
    };
    /** GetUserSessionInfoNestedReturn */
    GetUserSessionInfoNestedReturn: {
      auth: components["schemas"]["GetUserSessionInfoReturn"];
    };
    /** GetUserSessionInfoReturn */
    GetUserSessionInfoReturn: {
      user: components["schemas"]["UserPrivate"] | null;
      /** Scope Ids */
      scope_ids: number[] | null;
      access_token: components["schemas"]["UserAccessTokenPublic"] | null;
    };
    /** HTTPValidationError */
    HTTPValidationError: {
      /** Detail */
      detail?: components["schemas"]["ValidationError"][];
    };
    /** HomePageResponse */
    HomePageResponse: {
      auth: components["schemas"]["GetUserSessionInfoReturn"];
    };
    /** IsAvailableResponse */
    IsAvailableResponse: {
      /** Available */
      available: boolean;
    };
    /** LoginWithGoogleRequest */
    LoginWithGoogleRequest: {
      /** Id Token */
      id_token: string;
    };
    /** LoginWithGoogleResponse */
    LoginWithGoogleResponse: {
      auth: components["schemas"]["GetUserSessionInfoReturn"];
    };
    /** LoginWithMagicLinkRequest */
    LoginWithMagicLinkRequest: {
      /** Token */
      token: string;
    };
    /** LoginWithMagicLinkResponse */
    LoginWithMagicLinkResponse: {
      auth: components["schemas"]["GetUserSessionInfoReturn"];
    };
    /** LoginWithOTPEmailRequest */
    LoginWithOTPEmailRequest: {
      /** Code */
      code: string;
      /**
       * Email
       * Format: email
       */
      email: string;
    };
    /** LoginWithOTPPhoneNumberRequest */
    LoginWithOTPPhoneNumberRequest: {
      /** Code */
      code: string;
      /** Phone Number */
      phone_number: string;
    };
    /** LoginWithPasswordResponse */
    LoginWithPasswordResponse: {
      auth: components["schemas"]["GetUserSessionInfoReturn"];
    };
    /** PostLoginWithOTPResponse */
    PostLoginWithOTPResponse: {
      auth: components["schemas"]["GetUserSessionInfoReturn"];
    };
    /** ProfilePageResponse */
    ProfilePageResponse: {
      auth: components["schemas"]["GetUserSessionInfoReturn"];
      user?: components["schemas"]["UserPrivate"] | null;
    };
    /** RequestMagicLinkEmailRequest */
    RequestMagicLinkEmailRequest: {
      /**
       * Email
       * Format: email
       */
      email: string;
    };
    /** RequestMagicLinkSMSRequest */
    RequestMagicLinkSMSRequest: {
      /** Phone Number */
      phone_number: string;
    };
    /** RequestOTPEmailRequest */
    RequestOTPEmailRequest: {
      /**
       * Email
       * Format: email
       */
      email: string;
    };
    /** RequestOTPSMSRequest */
    RequestOTPSMSRequest: {
      /** Phone Number */
      phone_number: string;
    };
    /** RequestSignUpEmailRequest */
    RequestSignUpEmailRequest: {
      /**
       * Email
       * Format: email
       */
      email: string;
    };
    /** SettingsApiKeysPageResponse */
    SettingsApiKeysPageResponse: {
      auth: components["schemas"]["GetUserSessionInfoReturn"];
      /** Api Key Count */
      api_key_count: number;
      /** Api Keys */
      api_keys: components["schemas"]["ApiKeyPrivate"][];
    };
    /** SettingsPageResponse */
    SettingsPageResponse: {
      auth: components["schemas"]["GetUserSessionInfoReturn"];
    };
    /** SettingsUserAccessTokensPageResponse */
    SettingsUserAccessTokensPageResponse: {
      auth: components["schemas"]["GetUserSessionInfoReturn"];
      /** User Access Token Count */
      user_access_token_count: number;
      /** User Access Tokens */
      user_access_tokens: components["schemas"]["UserAccessToken"][];
    };
    /** SignUpRequest */
    SignUpRequest: {
      /** Token */
      token: string;
    };
    /** SignUpResponse */
    SignUpResponse: {
      auth: components["schemas"]["GetUserSessionInfoReturn"];
    };
    /** StylesPageResponse */
    StylesPageResponse: {
      auth: components["schemas"]["GetUserSessionInfoReturn"];
    };
    /** TokenResponse */
    TokenResponse: {
      /** Access Token */
      access_token: string;
      /** Token Type */
      token_type: string;
    };
    /** UserAccessToken */
    UserAccessToken: {
      /**
       * Issued
       * Format: date-time
       */
      issued: string;
      /**
       * Expiry
       * Format: date-time
       */
      expiry: string;
      /** User Id */
      user_id: string;
      /** Id */
      id: string;
    };
    /** UserAccessTokenAdminCreate */
    UserAccessTokenAdminCreate: {
      /**
       * Expiry
       * Format: date-time
       */
      expiry: string;
      /** User Id */
      user_id: string;
    };
    /** UserAccessTokenPublic */
    UserAccessTokenPublic: {
      /** Id */
      id: string;
      /**
       * Expiry
       * Format: date-time
       */
      expiry: string;
    };
    /** UserAdminCreate */
    UserAdminCreate: {
      /** Phone Number */
      phone_number?: string | null;
      /** Username */
      username?: string | null;
      /** Password */
      password?: string | null;
      /**
       * Email
       * Format: email
       */
      email: string;
      /**
       * User Role Id
       * @default 1
       */
      user_role_id?: number;
    };
    /** UserAdminUpdate */
    UserAdminUpdate: {
      /** Phone Number */
      phone_number?: string | null;
      /** Username */
      username?: string | null;
      /** Password */
      password?: string | null;
      /** Email */
      email?: string | null;
      /** User Role Id */
      user_role_id?: number | null;
    };
    /** UserPrivate */
    UserPrivate: {
      /** Id */
      id: string;
      /** Username */
      username?: string | null;
      /**
       * Email
       * Format: email
       */
      email: string;
      /** User Role Id */
      user_role_id: number;
    };
    /** UserPublic */
    UserPublic: {
      /** Id */
      id: string;
      /** Username */
      username?: string | null;
    };
    /** UserUpdate */
    UserUpdate: {
      /** Phone Number */
      phone_number?: string | null;
      /** Username */
      username?: string | null;
      /** Password */
      password?: string | null;
      /** Email */
      email?: string | null;
    };
    /** ValidationError */
    ValidationError: {
      /** Location */
      loc: (string | number)[];
      /** Message */
      msg: string;
      /** Error Type */
      type: string;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}

export type $defs = Record<string, never>;

export type external = Record<string, never>;

export interface operations {

  /** Auth Root */
  auth_root_auth__get: {
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["GetUserSessionInfoNestedReturn"];
        };
      };
    };
  };
  /** Token */
  token_auth_token__post: {
    requestBody: {
      content: {
        "application/x-www-form-urlencoded": components["schemas"]["Body_token_auth_token__post"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["TokenResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Login Password */
  login_password_auth_login_password__post: {
    requestBody: {
      content: {
        "application/x-www-form-urlencoded": components["schemas"]["Body_login_password_auth_login_password__post"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["LoginWithPasswordResponse"];
        };
      };
      /** @description Could not validate credentials */
      401: {
        content: {
          "application/json": components["schemas"]["DetailOnlyResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Login Magic Link */
  login_magic_link_auth_login_magic_link__post: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["LoginWithMagicLinkRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["LoginWithMagicLinkResponse"];
        };
      };
      /** @description Invalid token */
      401: {
        content: {
          "application/json": components["schemas"]["DetailOnlyResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Login Otp Email */
  login_otp_email_auth_login_otp_email__post: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["LoginWithOTPEmailRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["PostLoginWithOTPResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Login Otp Phone Number */
  login_otp_phone_number_auth_login_otp_phone_number__post: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["LoginWithOTPPhoneNumberRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["PostLoginWithOTPResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Signup */
  signup_auth_signup__post: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["SignUpRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["SignUpResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Login Google */
  login_google_auth_login_google__post: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["LoginWithGoogleRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["LoginWithGoogleResponse"];
        };
      };
      /** @description Invalid token */
      400: {
        content: {
          "application/json": components["schemas"]["DetailOnlyResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Request Sign Up Email */
  request_sign_up_email_auth_request_signup__post: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["RequestSignUpEmailRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": unknown;
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Request Magic Link Email */
  request_magic_link_email_auth_request_magic_link_email__post: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["RequestMagicLinkEmailRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": unknown;
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Request Magic Link Sms */
  request_magic_link_sms_auth_request_magic_link_sms__post: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["RequestMagicLinkSMSRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": unknown;
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Request Otp Email */
  request_otp_email_auth_request_otp_email__post: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["RequestOTPEmailRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": unknown;
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Request Otp Sms */
  request_otp_sms_auth_request_otp_sms__post: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["RequestOTPSMSRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": unknown;
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Logout */
  logout_auth_logout__post: {
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["DetailOnlyResponse"];
        };
      };
    };
  };
  /** List */
  list_users__get: {
    parameters: {
      query?: {
        /** @description Quantity of results */
        limit?: number;
        /** @description Index of the first result */
        offset?: number;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["UserPublic"][];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Get Me */
  get_me_users_me__get: {
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["UserPrivate"];
        };
      };
    };
  };
  /** Delete Me */
  delete_me_users_me__delete: {
    responses: {
      /** @description Successful Response */
      204: {
        content: never;
      };
    };
  };
  /** Update Me */
  update_me_users_me__patch: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["UserUpdate"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["UserPrivate"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** By Id */
  by_id_users__user_id___get: {
    parameters: {
      path: {
        user_id: string;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["UserPublic"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Check Username Availability */
  check_username_availability_users_available_username__username___get: {
    parameters: {
      path: {
        username: string;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": unknown;
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** List */
  list_galleries__get: {
    parameters: {
      query?: {
        /** @description Quantity of results */
        limit?: number;
        /** @description Index of the first result */
        offset?: number;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["GalleryPrivate"][];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Create */
  create_galleries__post: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["GalleryCreate"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["GalleryPrivate"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** By Id */
  by_id_galleries__gallery_id___get: {
    parameters: {
      path: {
        gallery_id: string;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["GalleryPublic"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Delete */
  delete_galleries__gallery_id___delete: {
    parameters: {
      path: {
        gallery_id: string;
      };
    };
    responses: {
      /** @description Successful Response */
      204: {
        content: never;
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Update */
  update_galleries__gallery_id___patch: {
    parameters: {
      path: {
        gallery_id: string;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["GalleryUpdate"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["GalleryPrivate"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Check Availability */
  check_availability_galleries_details_available__get: {
    parameters: {
      query: {
        name: string;
        parent_id?: string | null;
        date?: string | null;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": unknown;
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Upload File */
  upload_file_galleries__gallery_id__upload__post: {
    parameters: {
      path: {
        gallery_id: string;
      };
    };
    requestBody: {
      content: {
        "multipart/form-data": components["schemas"]["Body_upload_file_galleries__gallery_id__upload__post"];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        content: {
          "application/json": unknown;
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Sync */
  sync_galleries__gallery_id__sync__post: {
    parameters: {
      path: {
        gallery_id: string;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["DetailOnlyResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** List */
  list_user_access_tokens__get: {
    parameters: {
      query?: {
        /** @description Quantity of results */
        limit?: number;
        /** @description Index of the first result */
        offset?: number;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["UserAccessToken"][];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** By Id */
  by_id_user_access_tokens__user_access_token_id___get: {
    parameters: {
      path: {
        user_access_token_id: string;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["UserAccessToken"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Delete */
  delete_user_access_tokens__user_access_token_id___delete: {
    parameters: {
      path: {
        user_access_token_id: string;
      };
    };
    responses: {
      /** @description Successful Response */
      204: {
        content: never;
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Count */
  count_user_access_tokens_details_count__get: {
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": number;
        };
      };
    };
  };
  /** List */
  list_api_keys__get: {
    parameters: {
      query?: {
        /** @description Quantity of results */
        limit?: number;
        /** @description Index of the first result */
        offset?: number;
        /** @description Ordered series of fields to sort the results by, in the order they should be applied */
        order_by?: string[];
        /** @description Unordered series of fields which should be sorted in a descending manner, must be a subset of "order_by" fields */
        order_by_desc?: string[];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["ApiKeyPrivate"][];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Create */
  create_api_keys__post: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["ApiKeyCreate"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["ApiKeyPrivate"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** By Id */
  by_id_api_keys__api_key_id___get: {
    parameters: {
      path: {
        api_key_id: string;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["ApiKeyPrivate"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Delete */
  delete_api_keys__api_key_id___delete: {
    parameters: {
      path: {
        api_key_id: string;
      };
    };
    responses: {
      /** @description Successful Response */
      204: {
        content: never;
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Update */
  update_api_keys__api_key_id___patch: {
    parameters: {
      path: {
        api_key_id: string;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["ApiKeyUpdate"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["ApiKeyPrivate"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Jwt */
  jwt_api_keys__api_key_id__generate_jwt__get: {
    parameters: {
      path: {
        api_key_id: string;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["ApiKeyJWTResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Check Availability */
  check_availability_api_keys_details_available__get: {
    parameters: {
      query: {
        name: string;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["IsAvailableResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Count */
  count_api_keys_details_count__get: {
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": number;
        };
      };
    };
  };
  /** Add Scope To Api Key */
  add_scope_to_api_key_api_key_scopes_api_keys__api_key_id__scopes__scope_id___post: {
    parameters: {
      path: {
        api_key_id: string;
        scope_id: number;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": unknown;
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Remove Scope From Api Key */
  remove_scope_from_api_key_api_key_scopes_api_keys__api_key_id__scopes__scope_id___delete: {
    parameters: {
      path: {
        api_key_id: string;
        scope_id: number;
      };
    };
    responses: {
      /** @description Successful Response */
      204: {
        content: never;
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Profile */
  profile_pages_profile__get: {
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["ProfilePageResponse"];
        };
      };
    };
  };
  /** Home */
  home_pages_home__get: {
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["HomePageResponse"];
        };
      };
    };
  };
  /** Settings */
  settings_pages_settings__get: {
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["SettingsPageResponse"];
        };
      };
    };
  };
  /** Settings Api Keys */
  settings_api_keys_pages_settings_api_keys__get: {
    parameters: {
      query?: {
        /** @description Quantity of results */
        limit?: number;
        /** @description Index of the first result */
        offset?: number;
        /** @description Ordered series of fields to sort the results by, in the order they should be applied */
        order_by?: string[];
        /** @description Unordered series of fields which should be sorted in a descending manner, must be a subset of "order_by" fields */
        order_by_desc?: string[];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["SettingsApiKeysPageResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Settings User Access Tokens */
  settings_user_access_tokens_pages_settings_user_access_tokens__get: {
    parameters: {
      query?: {
        /** @description Quantity of results */
        limit?: number;
        /** @description Index of the first result */
        offset?: number;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["SettingsUserAccessTokensPageResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Styles */
  styles_pages_styles__get: {
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["StylesPageResponse"];
        };
      };
    };
  };
  /** Gallery */
  gallery_pages_galleries__gallery_id___get: {
    parameters: {
      query?: {
        root?: boolean;
      };
      path: {
        gallery_id: string | null;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["GalleryPageResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** List */
  list_admin_users__get: {
    parameters: {
      query?: {
        /** @description Quantity of results */
        limit?: number;
        /** @description Index of the first result */
        offset?: number;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["UserPrivate"][];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Create */
  create_admin_users__post: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["UserAdminCreate"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["UserPrivate"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** By Id */
  by_id_admin_users__user_id___get: {
    parameters: {
      path: {
        user_id: string;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["UserPrivate"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Delete */
  delete_admin_users__user_id___delete: {
    parameters: {
      path: {
        user_id: string;
      };
    };
    responses: {
      /** @description Successful Response */
      204: {
        content: never;
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Update */
  update_admin_users__user_id___patch: {
    parameters: {
      path: {
        user_id: string;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["UserAdminUpdate"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["UserPrivate"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** By Id */
  by_id_admin_galleries__gallery_id___get: {
    parameters: {
      path: {
        gallery_id: string;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["GalleryPrivate"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Delete */
  delete_admin_galleries__gallery_id___delete: {
    parameters: {
      path: {
        gallery_id: string;
      };
    };
    responses: {
      /** @description Successful Response */
      204: {
        content: never;
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Update */
  update_admin_galleries__gallery_id___patch: {
    parameters: {
      path: {
        gallery_id: string;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["GalleryAdminUpdate"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["GalleryPrivate"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Create */
  create_admin_galleries__post: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["GalleryAdminCreate"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["GalleryPrivate"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Check Availability */
  check_availability_admin_galleries_details_available__get: {
    parameters: {
      query: {
        name: string;
        parent_id?: string | null;
        date?: string | null;
        user_id: string;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": unknown;
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** List By User */
  list_by_user_admin_galleries_users__user_id__get: {
    parameters: {
      query?: {
        /** @description Quantity of results */
        limit?: number;
        /** @description Index of the first result */
        offset?: number;
      };
      path: {
        user_id: string;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["GalleryPrivate"][];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** List By User */
  list_by_user_admin_user_access_tokens_users__user_id___get: {
    parameters: {
      query?: {
        /** @description Quantity of results */
        limit?: number;
        /** @description Index of the first result */
        offset?: number;
      };
      path: {
        user_id: string;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["UserAccessToken"][];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** By Id */
  by_id_admin_user_access_tokens__user_access_token_id___get: {
    parameters: {
      path: {
        user_access_token_id: string;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["UserAccessToken"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Delete */
  delete_admin_user_access_tokens__user_access_token_id___delete: {
    parameters: {
      path: {
        user_access_token_id: string;
      };
    };
    responses: {
      /** @description Successful Response */
      204: {
        content: never;
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Create */
  create_admin_user_access_tokens__post: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["UserAccessTokenAdminCreate"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["UserAccessToken"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** List By User */
  list_by_user_admin_api_keys_users__user_id___get: {
    parameters: {
      query?: {
        /** @description Quantity of results */
        limit?: number;
        /** @description Index of the first result */
        offset?: number;
        /** @description Ordered series of fields to sort the results by, in the order they should be applied */
        order_by?: string[];
        /** @description Unordered series of fields which should be sorted in a descending manner, must be a subset of "order_by" fields */
        order_by_desc?: string[];
      };
      path: {
        user_id: string;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["ApiKeyPrivate"][];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** By Id */
  by_id_admin_api_keys__api_key_id___get: {
    parameters: {
      path: {
        api_key_id: string;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["ApiKeyPrivate"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Delete */
  delete_admin_api_keys__api_key_id___delete: {
    parameters: {
      path: {
        api_key_id: string;
      };
    };
    responses: {
      /** @description Successful Response */
      204: {
        content: never;
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Update */
  update_admin_api_keys__api_key_id___patch: {
    parameters: {
      path: {
        api_key_id: string;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["ApiKeyAdminUpdate"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["ApiKeyPrivate"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Create */
  create_admin_api_keys__post: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["ApiKeyAdminCreate"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["ApiKeyPrivate"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Check Availability */
  check_availability_admin_api_keys_details_available__get: {
    parameters: {
      query: {
        name: string;
        user_id: string;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": unknown;
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Add Scope To Api Key */
  add_scope_to_api_key_admin_api_key_scopes_api_keys__api_key_id__scopes__scope_id___post: {
    parameters: {
      path: {
        api_key_id: string;
        scope_id: number;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": unknown;
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Remove Scope From Api Key */
  remove_scope_from_api_key_admin_api_key_scopes_api_keys__api_key_id__scopes__scope_id___delete: {
    parameters: {
      path: {
        api_key_id: string;
        scope_id: number;
      };
    };
    responses: {
      /** @description Successful Response */
      204: {
        content: never;
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
}
